spring:
  application:
    name: spring-cloud-web-admin-feign

  zipkin:
    base-url: http://localhost:9411

server:
  port: 8508

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8501/eureka/
feign:
  hystrix:
    enabled: true
