spring:
  application:
    name: spring-cloud-web-admin-feign

server:
  port: 8507

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8501/eureka/
feign:
  hystrix:
    enabled: true
